# Generated by Django 5.0.6 on 2024-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('year_of_birth', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default='MALE', max_length=10, null=True)),
                ('aadharno', models.CharField(max_length=20, null=True)),
                ('fathers_name', models.CharField(max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('dob', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(default='Male', max_length=1)),
                ('aadharno', models.CharField(max_length=20, null=True)),
                ('fathers_name', models.CharField(max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('residence_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(default='MALE', max_length=10)),
                ('insurance_number', models.CharField(max_length=50, null=True)),
                ('insurance_holder_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
