# Generated by Django 5.0.6 on 2024-06-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0002_adhar_businesscard_kyc_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhar',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
