# Generated by Django 5.0.6 on 2024-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0004_alter_adhar_aadharno_alter_adhar_fathers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
