# Generated by Django 5.0.6 on 2024-06-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0005_alter_kyc_dob_alter_kyc_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhar',
            name='fathers_name',
        ),
    ]
